"""Contracts for the independent chassis execution surrogate project."""

from .contracts import (
    CHASSIS_STATE_FIELDS,
    COMMAND_TIMES_S,
    CONTROLLER_CONTEXT_FIELDS,
    CONTROL_FIELDS,
    EXECUTION_TIMES_S,
    INITIAL_STATE_FIELDS,
    VEHICLE_CONDITION_FIELDS,
    ChassisExecutionCommand,
    ChassisExecutionMemberPrediction,
    ChassisExecutionPrediction,
    ChassisExecutionSurrogate,
    ChassisExecutionTarget,
    ChassisExecutionContractError,
    aggregate_ensemble_predictions,
)
from .dataset import (
    ChassisExecutionDatasetMetadata,
    ChassisExecutionDatasetError,
    assign_run_group_split,
    canonical_sha256,
    validate_atomic_run_group_splits,
)
from .trucksim_exchange import (
    TruckSimExportError,
    VerifiedTruckSimRun,
    convert_verified_run,
    load_trucksim_export,
    verify_trucksim_export_root,
)
from .storage import (
    ChassisExecutionDataset,
    ChassisExecutionSampleIdentity,
    ChassisExecutionStorageError,
    ChassisExecutionStorageProvenance,
    verify_chassis_execution_dataset,
    write_chassis_execution_dataset,
)
from .surrogate import (
    ChassisExecutionEnsemble,
    ChassisExecutionMember,
    ChassisFeatureNormalizer,
    ChassisSurrogateConfig,
    ChassisSurrogateError,
    command_to_dense,
)
from .grpo_adapter import (
    ChassisExecutionContext,
    ChassisFusionGRPOAdapter,
    ChassisFusionGRPOError,
    ChassisFusionGRPOStepResult,
)

__all__ = [
    "CHASSIS_STATE_FIELDS",
    "COMMAND_TIMES_S",
    "CONTROLLER_CONTEXT_FIELDS",
    "CONTROL_FIELDS",
    "EXECUTION_TIMES_S",
    "INITIAL_STATE_FIELDS",
    "VEHICLE_CONDITION_FIELDS",
    "ChassisExecutionCommand",
    "ChassisExecutionContractError",
    "ChassisExecutionDatasetError",
    "ChassisExecutionDatasetMetadata",
    "ChassisExecutionMemberPrediction",
    "ChassisExecutionPrediction",
    "ChassisExecutionSurrogate",
    "ChassisExecutionTarget",
    "aggregate_ensemble_predictions",
    "assign_run_group_split",
    "canonical_sha256",
    "validate_atomic_run_group_splits",
    "TruckSimExportError",
    "VerifiedTruckSimRun",
    "convert_verified_run",
    "load_trucksim_export",
    "verify_trucksim_export_root",
    "ChassisExecutionDataset",
    "ChassisExecutionSampleIdentity",
    "ChassisExecutionStorageError",
    "ChassisExecutionStorageProvenance",
    "verify_chassis_execution_dataset",
    "write_chassis_execution_dataset",
    "ChassisExecutionEnsemble",
    "ChassisExecutionMember",
    "ChassisFeatureNormalizer",
    "ChassisSurrogateConfig",
    "ChassisSurrogateError",
    "command_to_dense",
    "ChassisExecutionContext",
    "ChassisFusionGRPOAdapter",
    "ChassisFusionGRPOError",
    "ChassisFusionGRPOStepResult",
]
