pretrained_ckpt: /media/kong/Elements_SE/Diffusion_Data/outputs/diffusion/run_6/checkpoints/diffusion-epoch=52.ckpt
anchor_path: metadrive/exp_dataset/anchors.npy
model_size: small
ego_fut_mode: 10
num_agents: 3
num_modes: 10  # mode slot数量，与 transfuser_config.py 的 NUM_MODE_SLOTS 保持一致
traffic_density: 0.08
num_scenarios: 1
use_hybrid_map: true
use_render: false
observation_mode: multimodal
planner_device: cuda

lambda_local: 0.1   # 本地奖励权重
lambda_team: 0.9    # 团队奖励权重

lr: 3.0e-4
gamma: 0.99
lambda_gae: 0.95
clip_param: 0.2
entropy_coeff: 0.01
vf_loss_coeff: 0.5
train_batch_size: 1024  # *每次训练迭代中使用的总样本数
sgd_minibatch_size: 256
num_sgd_iter: 10  # 一批数据训练多少次
num_rollout_workers: 4  # *
num_envs_per_worker: 1  # *
rollout_fragment_length: auto  # = train_batch_size // (num_rollout_workers * num_envs_per_worker)  # 每个worker每次采集多少步数据
max_iterations: 500
checkpoint_freq: 2  # 每多少次iteration保存一次ckpt
best_checkpoint_metric: episode_reward_mean
best_checkpoint_mode: max
num_gpus: 0.5
output_root: /media/kong/Elements_SE/Diffusion_Data/outputs/selector

reward_config:
  delta_s_max: 10.0
  d_norm: 10.0
  d_safe: 8.0
  w_progress: 0.8
  w_formation: 1.0
  w_safety: 0.8
  w_collision: 10.0
  w_road: 5.0
  w_comfort: 0.05
  w_team_formation: 1.0
  w_team_safety: 1.5
  w_team_efficiency: 0.2
  w_team_collision: 10.0
  reward_clip: 8.0
